<?php 
session_start();
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

header('Content-Type: application/json');

$response = array('success' => false, 'message' => '');

if (isset($_POST['tableData'])) {
    require 'vendor/autoload.php';
    require 'credential.php';

    $tableData = $_POST['tableData'];  // Raw table data
    $searchQuery = $_POST['searchQuery'];
    $assetType = $_POST['assetType'];
    $recipients = $_POST['recipients'];
    $customMessage = $_POST['customMessage'];

    // Retrieve first name and last name from session
    $firstname = isset($_SESSION['firstname']) ? $_SESSION['firstname'] : 'User';
    $lastname = isset($_SESSION['lastname']) ? $_SESSION['lastname'] : '';

    // Initialize PHPMailer
    $mail = new PHPMailer;
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = EMAIL;
    $mail->Password = PASS;
    $mail->SMTPSecure = 'tls';
    $mail->Port = 587;

    // Sender
    $mail->setFrom(EMAIL, 'APAC ASSET SYSTEM');

    // Recipients
    $recipientList = explode(",", $recipients); // Comma-separated email addresses
    foreach ($recipientList as $recipient) {
        $mail->addAddress(trim($recipient));
    }

    // Subject
    $mail->isHTML(true);                                  
    $mail->Subject = 'APAC Asset Results';

    // Email body
    $mail->Body = '<div style="font-family: Arial, sans-serif; width: 100%; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); background-color: #fff;">
                      <div style="background-color:#191a40; padding: 20px; text-align: center;">
                          <img src="cid:logo" alt="APAC Logo" style="width:100px; height:auto;"/>
                          <h2 style="color: white;">APAC Asset System</h2>
                      </div>
                      <div style="padding: 20px;">
                          <p>This is the list of asset(s) requested by: <strong>' . htmlspecialchars($firstname . ' ' . $lastname) . '</strong></p>
                          <p><strong>Search Query:</strong> ' . htmlspecialchars($searchQuery) . '</p>
                          <p><strong>Asset Type:</strong> ' . htmlspecialchars($assetType) . '</p>';

    // Asset Data
    $mail->Body .= '<table>' . $tableData . '</table>';

    // Custom message
    if (!empty($customMessage)) {
        $mail->Body .= '<br><p>' . nl2br(htmlspecialchars($customMessage)) . '</p>';
    }

    // Autogenerated note
    $mail->Body .= '<p style="font-size:14px; color:#555;">This is an auto-generated email. Replies will not be monitored.</p>';

    // Attach logo image
    $mail->addEmbeddedImage($_SERVER['DOCUMENT_ROOT'].'/dashboard/logo.png', 'logo');

    // Handle attachment
    if (isset($_FILES['attachment']) && $_FILES['attachment']['error'] == UPLOAD_ERR_OK) {
        $mail->addAttachment($_FILES['attachment']['tmp_name'], $_FILES['attachment']['name']);
    }

    // Send email
    if (!$mail->send()) {
        $response['message'] = 'Mailer Error: ' . $mail->ErrorInfo;
    } else {
        $response['success'] = true;
        $response['message'] = 'Message has been sent';
    }

    // Return JSON response
    echo json_encode($response);
    exit;
} else {
    $response['message'] = 'No data received.';
    echo json_encode($response);
    exit;
}
?>
